repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
      - id: seed-isort-config
        args: ['--application-directories', 'src']

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        files: ^src/
        exclude: src/waldur_core/server/base_settings.py

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        files: ^src/
        exclude: src/waldur_core/server/base_settings.py

  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        files: ^src/
        exclude: src/waldur_core/server/base_settings.py
        additional_dependencies:
          - flake8-bandit==2.1.0
