language: python

services:
- docker

install:
- echo "Everything is described in Dockerfile. Overriding default install script."

script:
- echo "No need to run tests, they are run externally."

deploy:
- provider: script
  script: bash docker_push.sh
  on:
    branch: develop

- provider: script
  script: bash docker_push.sh $TRAVIS_TAG
  on:
    tags: true

env:
  global:
  - secure: PDBFfnhoNCCCnkWNf2TJsTguy3dZlMfjFLqTNlhPDDgS8QwXqScF85r6sEj1uDToaWv5E8zbnSCfKDpDyHB3uRDgNdd8xUt/rx/dZjF63g0/DJEBHMd2pk4HsWHO0d2JDhubyAlBsfo1Db6cmGFQigBW+Y+V8Ny+C7+Dy7DkleeSFVFg2OS6kBYlXOZJtYLQumsFnMupMbvcej2wCXWNGfOMUtXaIE3iUTByRu0as4hVNFvd7jIX2+gcOAgmLX1W4wgPiG9NvaQAedoZZdRphAS7ycMmAZr6C2RfE51tOBHoy6dMibknJaafORg9f5U3k0RaaNx1vX5yyhwyAWrYlRP/HNzgwD8dMPWNMZzKJ6cJd79o6G7y7i7uUPC0sbuOKRsJR+cmpfVffgrrT/XfcZI6U61CFyffurIlkJAIcH6gixfmgkqSOi3mxwdRmyHjuecIH2U+Tpz2FOHEHj/VN2/VIx7cLaxEzhQ7vdY9dQB35obidM6voo35VN18Tip6/3KOcXUz98rhOdUeVsUUjp7Ubv/47f7srYj4dOLYQ7nwGYeEvWsTIwCdTdmo7lsOT6NMjUEFhC9iXxTaZXkUQj+3UIRo3LRlgQu9BmNXaXd6M8uDAb7BqTbUkzQrGUe3uLS1s6RoYO5Rxeh1f3kJo0T6L7s8I53DCB5dabE4UN0=
  - secure: YUkYCnOlcNKL5ii3kTCBwK/SmfNlao19yG1hMXxRrakvQ0+FPs2BxRH6Hoqxw371Ly6TYVG7nDguwqOZm7EZeB5IVE0NxzrB/Jb/iTqaRlq7/T8PZmnEdqMowZ1Rpwew1A7hhyfx9TqkC1a5EwJq4IgAlBDttx0hwVmTIzq2G3rCiNE+0jWf4wMRpmZYMsVUfku0313fNgcSeR9p4QKXlPDEoFWZFtJ5Yq0Imzyd0DrF2gZurK7DKgShc2hO5e/RayMI1gNqazTR3t96rIpp2QuaPdNh4kPM9DKDhr1BKcdLT4ielpom3uTVI7C0rYGA/N/DZugMNJgoSl2mc+861XRNNDrDT+WhdfxW4bvZI0NNUWgVNPhiEWO02oPyRdoJRmh3DLAk9cbQwU/5pTHFAfAsBUCY7It72YPmFDWxhb89f0HWBzTduA68qNSM+tqzdTkHu3rzb720gb/QkCCcZYBo0bOK+6LLnPsQPqTd6fNwSuGFZFv9ieUVA4ODjBAY005dzJIeYrjMePaLf7B4b8t8ToGiMvUVJL/gwgzQhGAHogecXIz96eX+XRgzfz/NcBP888nUha46vV0uzotIXTTOn2IzZ4RdOotxxDQxVDCipMeZeoNtLIcjmERQLU+BOxo6jgzYw8HzMnB/Y8Ha5dgb1T0ZbGBGXaSmkmN3s/E=
