version: '3'

services:
  db:
    build:
      context: db
    environment:
      - POSTGRESQL_DATABASE=test_waldur
      - POSTGRESQL_USER=root
      - POSTGRESQL_PASSWORD=waldur
    ports:
      - "5432"
    tmpfs: /var/lib/postgresql/data

  api:
    build:
      context: api
    volumes:
      - ../:/mnt
      - ./pip-cache/:/tmp/pip-cache/
    links:
      - db

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
