# Generated by Django 6.0.8 on 2026-09-13 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0288_drop_azure_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceMemberSyncReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_at", models.DateTimeField()),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_sync_report",
                        to="marketplace.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource member sync report",
                "verbose_name_plural": "Resource member sync reports",
            },
        ),
    ]
