# Generated by Django 4.2.20 on 2025-04-27 07:01

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import waldur_core.core.fields
import waldur_core.core.models
import waldur_core.structure.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0052_accesssubnet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenNebulaTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', waldur_core.core.fields.UUIDField()),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(5, 'CREATION_SCHEDULED'), (6, 'CREATING'), (1, 'UPDATE_SCHEDULED'), (2, 'UPDATING'), (7, 'DELETION_SCHEDULED'), (8, 'DELETING'), (3, 'OK'), (4, 'ERRED')], default=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('backend_id', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.project')),
                ('service_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.servicesettings')),
            ],
            options={
                'verbose_name': 'OpenNebula Tenant',
                'verbose_name_plural': 'OpenNebula Tenants',
                'unique_together': {('service_settings', 'backend_id')},
            },
            bases=(waldur_core.core.models.DescendantMixin, waldur_core.core.models.BackendModelMixin, waldur_core.structure.models.StructureLoggableMixin, models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name='OpenNebulaVirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', waldur_core.core.fields.UUIDField()),
                ('error_traceback', models.TextField(blank=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(5, 'CREATION_SCHEDULED'), (6, 'CREATING'), (1, 'UPDATE_SCHEDULED'), (2, 'UPDATING'), (7, 'DELETION_SCHEDULED'), (8, 'DELETING'), (3, 'OK'), (4, 'ERRED')], default=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('backend_id', models.CharField(blank=True, max_length=255)),
                ('cpu', models.PositiveIntegerField(default=1)),
                ('ram', models.PositiveIntegerField(default=1024, help_text='RAM in MB')),
                ('disk', models.PositiveIntegerField(default=10, help_text='Disk size in GB')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage for async operations.')),
                ('error_message', models.TextField(blank=True, help_text='Last error message, if any.', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.project')),
                ('service_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.servicesettings')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='opennebula.opennebulatenant')),
            ],
            options={
                'verbose_name': 'OpenNebula Virtual Machine',
                'verbose_name_plural': 'OpenNebula Virtual Machines',
                'unique_together': {('service_settings', 'backend_id')},
            },
            bases=(waldur_core.core.models.DescendantMixin, waldur_core.core.models.BackendModelMixin, waldur_core.structure.models.StructureLoggableMixin, models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name='OpenNebulaScheduledAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('snapshot', 'Snapshot'), ('backup', 'Backup')], max_length=16)),
                ('interval', models.CharField(max_length=16)),
                ('next_run', models.DateTimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opennebula.opennebulavirtualmachine')),
            ],
            options={
                'verbose_name': 'OpenNebula Scheduled Action',
                'verbose_name_plural': 'OpenNebula Scheduled Actions',
            },
        ),
        migrations.CreateModel(
            name='OpenNebulaVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', waldur_core.core.fields.UUIDField()),
                ('error_traceback', models.TextField(blank=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(5, 'CREATION_SCHEDULED'), (6, 'CREATING'), (1, 'UPDATE_SCHEDULED'), (2, 'UPDATING'), (7, 'DELETION_SCHEDULED'), (8, 'DELETING'), (3, 'OK'), (4, 'ERRED')], default=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('backend_id', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0, help_text='Size in GB')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage for async operations.')),
                ('error_message', models.TextField(blank=True, help_text='Last error message, if any.', null=True)),
                ('service_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.servicesettings')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='opennebula.opennebulatenant')),
            ],
            options={
                'verbose_name': 'OpenNebula Volume',
                'verbose_name_plural': 'OpenNebula Volumes',
                'unique_together': {('service_settings', 'backend_id')},
            },
            bases=(waldur_core.core.models.BackendModelMixin, waldur_core.structure.models.StructureLoggableMixin, models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
        migrations.CreateModel(
            name='OpenNebulaNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', waldur_core.core.fields.UUIDField()),
                ('error_traceback', models.TextField(blank=True)),
                ('state', django_fsm.FSMIntegerField(choices=[(5, 'CREATION_SCHEDULED'), (6, 'CREATING'), (1, 'UPDATE_SCHEDULED'), (2, 'UPDATING'), (7, 'DELETION_SCHEDULED'), (8, 'DELETING'), (3, 'OK'), (4, 'ERRED')], default=5)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('backend_id', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage for async operations.')),
                ('error_message', models.TextField(blank=True, help_text='Last error message, if any.', null=True)),
                ('service_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.servicesettings')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='opennebula.opennebulatenant')),
            ],
            options={
                'verbose_name': 'OpenNebula Network',
                'verbose_name_plural': 'OpenNebula Networks',
                'unique_together': {('service_settings', 'backend_id')},
            },
            bases=(waldur_core.core.models.BackendModelMixin, waldur_core.structure.models.StructureLoggableMixin, models.Model, django_fsm.ConcurrentTransitionMixin),
        ),
    ]
