# Generated by Django 4.2.20 on 2025-05-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opennebula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opennebulanetwork',
            options={'ordering': ['name', 'created'], 'verbose_name': 'OpenNebula Network', 'verbose_name_plural': 'OpenNebula Networks'},
        ),
        migrations.AlterModelOptions(
            name='opennebulascheduledaction',
            options={'ordering': ['last_run', 'next_run'], 'verbose_name': 'OpenNebula Scheduled Action', 'verbose_name_plural': 'OpenNebula Scheduled Actions'},
        ),
        migrations.AlterModelOptions(
            name='opennebulatenant',
            options={'ordering': ['name', 'created'], 'verbose_name': 'OpenNebula Tenant', 'verbose_name_plural': 'OpenNebula Tenants'},
        ),
        migrations.AlterModelOptions(
            name='opennebulavirtualmachine',
            options={'ordering': ['name', 'created'], 'verbose_name': 'OpenNebula Virtual Machine', 'verbose_name_plural': 'OpenNebula Virtual Machines'},
        ),
        migrations.AlterModelOptions(
            name='opennebulavolume',
            options={'ordering': ['name', 'created'], 'verbose_name': 'OpenNebula Volume', 'verbose_name_plural': 'OpenNebula Volumes'},
        ),
    ]
